some world stuff
Legacy-Fabric/yarn pull request #100
Opened 2021-01-24 08:11 UTC by BluCobalt

2021-01-25 06:55 UTC, DeadlyMC commented on mappings/net/minecraft/world/World.mapping
> +	METHOD method_336 pushPlayerLevelEvent (Lnet/minecraft/class_1963;ILnet/minecraft/class_1372;I)V
`syncWorldEvent` , checkout ClientWorld in 1.16

2021-01-25 06:55 UTC, DeadlyMC commented on mappings/net/minecraft/world/World.mapping
>  		ARG 2 type
`eventId`

2021-01-25 06:58 UTC, DeadlyMC commented on mappings/net/minecraft/world/World.mapping
> +	METHOD method_354 pushLevelEvent (ILnet/minecraft/class_1372;I)V
`syncGlobalEvent`, checkout ClientWorld

2021-01-25 06:58 UTC, DeadlyMC commented on mappings/net/minecraft/world/World.mapping
> +		ARG 1 type
eventId

2021-01-25 07:01 UTC, DeadlyMC commented on mappings/net/minecraft/world/WorldEventListener.mapping
> +	METHOD method_454 onBlockBreakInfo (ILnet/minecraft/class_1372;I)V
`setBlockBreakingInfo`, upstream

2021-01-25 07:02 UTC, DeadlyMC requested changes
Added single comments for the requested changes

2021-01-25 07:31 UTC, DeadlyMC approved these changes

2021-01-25 07:33 UTC, BluCobalt commented
@hYdos can you review this

2021-01-27 06:30 UTC, hYdos approved these changes

2021-01-27 06:30 UTC, merged