Some items and blocks mappings
Legacy-Fabric/yarn pull request #103
Opened 2021-02-06 11:20 UTC by arthurbambou

2021-02-06 22:12 UTC, hYdos approved these changes

2021-02-07 07:27 UTC, DeadlyMC requested changes
I highly suggest you look at upstream mappings if you make prs anytime again

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13233 SLIMEBALL Lnet/minecraft/class_2054;
SLIME_BALL

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13234 MINECART_CHEST Lnet/minecraft/class_2054;
CHEST_MINECART

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13235 MINECART_FURNACE Lnet/minecraft/class_2054;
FURNACE_MINECART

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13263 PORKCHOP_RAW Lnet/minecraft/class_2054;
PORKCHOP

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13264 PORKCHOP_COOKED Lnet/minecraft/class_2054;
COOKED_PORKCHOP

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13269 EMPTY_BUCKET Lnet/minecraft/class_2054;
BUCKET

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13274 SPECKLED_MELON Lnet/minecraft/class_2054;
GLISTERING_MELON_SLICE

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13276 XP_BOTTLE Lnet/minecraft/class_2054;
EXPERIENCE_BOTTLE

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13277 FIREBALL Lnet/minecraft/class_2054;
FIRE_CHARGE

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13283 CARROTS Lnet/minecraft/class_2054;
CARROT

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13284 POTATOES Lnet/minecraft/class_2054;
POTATO

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13287 EMPTY_MAP Lnet/minecraft/class_2038;
MAP

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13293 FIREWORK Lnet/minecraft/class_2054;
FIREWORK_ROCKET

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13294 FIREWORKS_CHARGE Lnet/minecraft/class_2054;
FIREWORK_STAR

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13302 MAP_FILLED Lnet/minecraft/class_4;
FILLED_MAP

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13307 RAW_BEEF Lnet/minecraft/class_2054;
BEEF

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13309 RAW_CHICKEN Lnet/minecraft/class_2054;
CHICKEN

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13318 EMPTY_BOTTLE Lnet/minecraft/class_2054;
GLASS_BOTTLE ?

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13325 MINECART_TNT Lnet/minecraft/class_2054;
TNT_MINECART

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13326 MINECART_HOPPER Lnet/minecraft/class_2054;
HOPPER_MINECART

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13343 RECORD_WAIT Lnet/minecraft/class_2054;
RECORD -> MUSIC_DISC

2021-02-07 07:27 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13361 WOOD_AXE Lnet/minecraft/class_2054;
WOOD -> WOODEN

2021-02-08 12:01 UTC, arthurbambou commented on mappings/net/minecraft/block/Block.mapping
> +	FIELD field_12066 GRAVEL_SOUND Lnet/minecraft/class_162;
Yes, block sounds seems to be registered in the same class as blocks

2021-02-08 12:02 UTC, arthurbambou commented on mappings/net/minecraft/block/Block.mapping
> +	FIELD field_12074 BLOCKS [Lnet/minecraft/class_160;
There is no registry class for blocks or items, should I call this one registry? It's a Block array

2021-02-08 13:47 UTC, DeadlyMC commented on mappings/net/minecraft/block/Block.mapping
> +	FIELD field_12066 GRAVEL_SOUND Lnet/minecraft/class_162;
oh wow, interesting. Then its fine

2021-02-08 13:48 UTC, DeadlyMC commented on mappings/net/minecraft/block/Block.mapping
> +	FIELD field_12074 BLOCKS [Lnet/minecraft/class_160;
Leave it as `BLOCKS`

2021-02-08 13:56 UTC, DeadlyMC requested changes
You forgot to remap one of them, otherwise all looks good.

2021-02-08 13:56 UTC, DeadlyMC commented on mappings/net/minecraft/item/Item.mapping
> +	FIELD field_13233 SLIMEBALL Lnet/minecraft/class_2054;
You forgot this one

2021-02-08 14:32 UTC, DeadlyMC approved these changes
Looks good! Thanks for the pr. Im gonna hold it until i change the buildscript to publish to our new maven instead of bintray

2021-02-18 14:58 UTC, arthurbambou commented
bump

2021-02-22 07:28 UTC, DeadlyMC commented
Thank you for the pr, merging now!

2021-02-22 07:28 UTC, merged