[1.8.9] Various net.minecraft.world.chunk mappings
Legacy-Fabric/yarn pull request #141
Opened 2021-08-25 22:54 UTC by Reselim

Still incomplete, but a little bit less now.

Most of these have been reverse engineered from scratch, however some mappings were taken from 1.17.x yarn.

2021-10-02 13:01 UTC, BoogieMonster1O1 approved these changes

2021-10-02 13:02 UTC, BoogieMonster1O1 commented
Is this ready for merge?

2021-10-02 17:29 UTC, Grayray75 requested changes
There are still some chunk y left

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/entity/MobSpawnerHelper.mapping
> +		ARG 2 chunkY
here

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/world/World.mapping
> +		ARG 2 chunkY
here

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/world/chunk/ServerChunkProvider.mapping
> +		ARG 2 chunkY
and here

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/world/chunk/ChunkProvider.mapping
> +		ARG 3 y
y => z

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/world/chunk/Chunk.mapping
> +		ARG 2 y
y => z

2021-10-02 17:29 UTC, Grayray75 commented on mappings/net/minecraft/world/dimension/Dimension.mapping
> +		ARG 2 y
y => z

2021-10-03 00:22 UTC, Reselim commented
done

2021-10-03 11:13 UTC, arthurbambou approved these changes

2021-10-03 18:20 UTC, Grayray75 approved these changes

2021-10-22 10:51 UTC, merged