So anyways I did a few mappings Part 2!
Legacy-Fabric/yarn pull request #191
Opened 2022-05-18 16:13 UTC by u9g

2022-05-18 19:35 UTC, arthurbambou requested changes

2022-05-18 19:35 UTC, arthurbambou commented on mappings/net/minecraft/utill/shape/VoxelSet.mapping
> +CLASS net/minecraft/class_4086 net/minecraft/utill/shape/VoxelSet
utill?

2022-05-18 19:35 UTC, arthurbambou commented on mappings/net/minecraft/utill/shape/SliceVoxelShape.mapping
> +CLASS net/minecraft/class_4098 net/minecraft/utill/shape/SliceVoxelShape
utill?

2022-05-18 19:39 UTC, u9g commented on mappings/net/minecraft/utill/shape/SliceVoxelShape.mapping
> +CLASS net/minecraft/class_4098 net/minecraft/utill/shape/SliceVoxelShape
fixed in 31215e0

2022-05-18 19:39 UTC, u9g commented on mappings/net/minecraft/utill/shape/VoxelSet.mapping
> +CLASS net/minecraft/class_4086 net/minecraft/utill/shape/VoxelSet
fixed in 31215e0

2022-05-19 14:30 UTC, arthurbambou reviewed
this seems to have created conflicts again....

2022-05-19 17:34 UTC, arthurbambou approved these changes

2022-05-21 10:57 UTC, BleachDrinker420 commented
Why rename Box to BoundingBox?

2022-05-21 17:05 UTC, u9g commented
> Why rename Box to BoundingBox?

I renamed box to boundingbox, since box was kind of vague, many things can be a box, a block is a box, a chest can be a box, etc. Should I change it back? It just made more sense to me this way.

2022-05-21 17:18 UTC, PhoenixVX commented
The more appropriate name would be AxisAlignedBoundingBox, AABB, or AxisAlignedBB like in MCP. This bounding box usually represents collision boxes rather than a generic box. BoundingBox is okay, but it doesn't really tell you that this bounding box is aligned to an axis.

2022-05-21 17:20 UTC, BleachDrinker420 commented
ITS A BOX

2022-05-21 17:21 UTC, PhoenixVX commented
A box doesn't tell you it's a hit box, a block box, an entity collision box... A form of Bounding Box is approriate.

2022-05-21 17:29 UTC, u9g commented
> The more appropriate name would be AxisAlignedBoundingBox, AABB, or AxisAlignedBB like in MCP. This bounding box usually represents collision boxes rather than a generic box. BoundingBox is okay, but it doesn't really tell you that this bounding box is aligned to an axis.

Can I use their axisalignedboundingbox name? aren’t I supposed to not take from mcp?

2022-05-21 17:29 UTC, u9g commented
AxisAlignedBox? ;p

2022-05-21 17:30 UTC, PhoenixVX commented
Mojang also uses that name. As for the legality of using it, that's quite hard to say since it's quite easy to determine that's the functionality of it is appropriately represented by such name, i.e. coming up with the same name wouldn't be far-fetched.

2022-05-21 17:31 UTC, BleachDrinker420 commented
Its just a box with 8 corners, it can be used for anything it doesn't need any more info, and the main priority should anyway be to match the upstream fabric mappings

2022-05-21 17:32 UTC, PhoenixVX commented
It used to be named BoundingBox in upstream, but it recently got changed to Box for some reason.

2022-05-21 17:33 UTC, PseudoDistant approved these changes
B O X

2022-05-21 17:36 UTC, u9g commented
ok ok I din’t have that strong of an opinion, I’ll call it Box

2022-05-21 17:48 UTC, BleachDrinker420 approved these changes

2022-05-21 19:35 UTC, arthurbambou approved these changes

2022-05-21 19:36 UTC, merged