[Yarn Rewrite] Added a script to separate the mappings before running gradle
Legacy-Fabric/yarn pull request #196
Opened 2022-05-29 19:19 UTC by BleachDrinker420

Added yarn.py which separates the mappings, runs a gradle command then merges the mappings back.

I've tested quite a few cases and everything seems to work fine. adding, renaming and deleting all works and fields, methods and classes with duplicated names also works fine but i'd still recommend to have some people test it before merging.

Since i used the start file from #194 that PR isn't needed anymore and should be closed if this one gets merged.

2022-05-29 19:27 UTC, BluCobalt commented on .github/workflows/build.yml
> +          distribution: 'temurin' # See 'Supported distributions' for available options
Openj9 tho

2022-05-29 19:43 UTC, arthurbambou requested changes
wont work on windows tho

2022-05-29 19:43 UTC, arthurbambou commented on yarn.py
> +    os.system("gradlew " + command)
```suggestion
    os.system("./gradlew " + command)
```

2022-05-29 20:09 UTC, arthurbambou commented
It seems like some conflicts slipped through before :flushed: on 1.11.2
```
Mapping source name conflicts detected:
  net/minecraft/class_3106 METHOD method_13872 ((Lnet/minecraft/class_3146;)Lnet/minecraft/class_1653;) -> [net/minecraft/class_3106/method_5745, net/minecraft/class_3106/method_5757, net/minecraft/class_3109/method_5757]
  net/minecraft/class_1357 METHOD method_5816 ((Lnet/minecraft/class_982;)Lnet/minecraft/class_1653;) -> [net/minecraft/class_1357/method_5745, net/minecraft/class_1357/method_5757]
  net/minecraft/class_3109 METHOD method_13872 ((Lnet/minecraft/class_3146;)Lnet/minecraft/class_1653;) -> [net/minecraft/class_3106/method_5757, net/minecraft/class_3109/method_5745, net/minecraft/class_3109/method_5757]
  net/minecraft/class_3103 METHOD method_5816 ((Lnet/minecraft/class_982;)Lnet/minecraft/class_1653;) -> [net/minecraft/class_1357/method_5745, net/minecraft/class_3103/method_5757]
  net/minecraft/class_1352 METHOD method_13872 ((Lnet/minecraft/class_3146;)Lnet/minecraft/class_1653;) -> [net/minecraft/class_3106/method_5757, net/minecraft/class_3109/method_5757, net/minecraft/class_1352/method_5745]
```

2022-05-30 11:19 UTC, BleachDrinker420 commented
The conflicts seems to be fixed, weird that it only happens when the methods are unmapped

2022-05-30 11:49 UTC, arthurbambou approved these changes

2022-05-30 22:24 UTC, merged