ItemStack mappings and some other things
Legacy-Fabric/yarn pull request #211
Opened 2022-09-11 21:14 UTC by BleachDev

**Changes:**
Added some mappings in ItemStack and related classes, including fixing these which might trip people up when updating mappings
`ItemStack.isDamaged` -> `ItemStack.isStackable`
`ItemStack.isEmpty` -> `ItemStack.isDamaged`
`ItemStack.isEmpty_` -> `ItemStack.isEmpty`

Removed some mappings in `net/minecraft/client/sound` which somehow were duplicate classes of ones in `net/minecraft/sound`

Updated the README instructions for launching Enigma

Fixed a bug in the merging script that caused it to fail when adding a mapping with a name that already exists in the same folder

2022-09-11 21:38 UTC, Wyvest requested changes

2022-09-11 21:38 UTC, Wyvest commented on mappings/net/minecraft/inventory/slot/Slot.mapping
> -	FIELD field_4154 yPosition I
shouldn't this just be posX and posY

2022-09-11 21:43 UTC, BleachDev commented on mappings/net/minecraft/inventory/slot/Slot.mapping
> -	FIELD field_4154 yPosition I
changed them to just x and y

2022-09-12 00:45 UTC, Wyvest approved these changes

2022-09-12 00:49 UTC, u9g approved these changes

2022-09-12 17:26 UTC, arthurbambou approved these changes

2022-09-15 13:24 UTC, BoogieMonster1O1 approved these changes

2022-09-15 13:24 UTC, merged