ender's 1.12.2 FullMappingAlchemist attempt
Legacy-Fabric/yarn pull request #212
Opened 2022-09-11 22:45 UTC by ENDERZOMBI102

- [] Fully map ui-related classes
- [] Fully map sound-related classes

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/entity/player/PlayerInventory.mapping
> +	METHOD method_13254 stacksAreEqual (Lnet/minecraft/class_1071;Lnet/minecraft/class_1071;)Z
`areStacksEqual` or `areEqual`, `stacksAreEqual` sounds pretty awkward

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/item/Item.mapping
> +		ARG 1 meta
getMeta(meta) is a bit sus

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/item/VariantBlockItem.mapping
> +		ARG 2 variantblock
```suggestion
		ARG 2 variantBlock
```

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/realms/RealmsClickableScrolledSelectionList.mapping
> +		ARG 2 yEnd
```suggestion
		ARG 1 startY
		ARG 2 endY
```
Naming conventions

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/sound/BlockSoundGroup.mapping
> +		ARG 6 hitSOund
```suggestion
		ARG 3 breakSound
		ARG 4 stepSound
		ARG 5 placeSound
		ARG 6 hitSound
```

2022-09-12 07:11 UTC, BleachDev commented on mappings/net/minecraft/sound/BlockSoundGroup.mapping
> +	FIELD field_12771 breakSOund Lnet/minecraft/class_2926;
```suggestion
	FIELD field_12771 breakSound Lnet/minecraft/class_2926;
```

2022-09-12 17:30 UTC, arthurbambou commented on mappings/net/minecraft/BlockItem.mapping
> +CLASS net/minecraft/class_3056 net/minecraft/BlockItem
Move in item package

2022-09-12 17:30 UTC, arthurbambou commented on mappings/net/minecraft/MagmaBlock.mapping
> +CLASS net/minecraft/class_3010 net/minecraft/MagmaBlock
Move in block package

2022-09-12 20:02 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/entity/player/PlayerInventory.mapping
> +	METHOD method_13254 stacksAreEqual (Lnet/minecraft/class_1071;Lnet/minecraft/class_1071;)Z
`areStacksEqual`

2022-09-12 20:04 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/item/Item.mapping
> +		ARG 1 meta
reset to obfuscated

2022-09-12 20:07 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/realms/RealmsClickableScrolledSelectionList.mapping
> +		ARG 2 yEnd
fixed the typo

2022-09-12 20:07 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/item/VariantBlockItem.mapping
> +		ARG 2 variantblock
fixed the typo

2022-09-12 20:09 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/realms/RealmsClickableScrolledSelectionList.mapping
> +		ARG 2 yEnd
done

2022-09-12 20:10 UTC, ENDERZOMBI102 commented on mappings/net/minecraft/sound/BlockSoundGroup.mapping
> +		ARG 6 hitSOund
typo fixed

2022-09-18 14:45 UTC, BoogieMonster1O1 requested changes
pls no large yarn prs. split into smaller ones
- easier to review
- no merge conflicts

2022-10-15 08:10 UTC, BoogieMonster1O1 commented
what must happen to this pr

2022-10-15 10:34 UTC, arthurbambou commented
Idk, it's still a draft

2022-10-15 14:57 UTC, closed without merging