move network/packet related classes in the package
Legacy-Fabric/yarn pull request #228
Opened 2022-09-23 15:40 UTC by johannes-schmatz

also name field_13783, see the other PR

2022-09-23 15:49 UTC, arthurbambou approved these changes

2022-09-23 16:13 UTC, BleachDev approved these changes

2022-09-25 14:18 UTC, BoogieMonster1O1 requested changes
https://wiki.vg/index.php?title=Protocol&oldid=13363
You can use this to help map the packet classes (it has a list of each packet id and packet name). I don't think they should remain unmapped in packages.

2022-09-26 11:46 UTC, arthurbambou approved these changes

2022-09-26 11:47 UTC, johannes-schmatz commented
now all packets are mapped

2022-10-04 20:02 UTC, merged